app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v0.8.4
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      hosts:
        - host: home.biggibson.cocotree.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - home.biggibson.cocotree.cc
  persistence:
    config:
      enabled: true
      type: configMap
      name: homepage-config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        kubernetes.yaml:
          mode: cluster
        settings.yaml: |
          background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
          cardBlur: md
          theme: dark
          headerStyle: boxed
          hideVersion: true
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
          - kubernetes:
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel:  true
                label: "cluster"
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true

        services.yaml: |
          - Development:
            - Github:
                href: https://github.com/captainsloths/gibsonkube
                description: The heart
                icon: github.svg
            - ArgoCD:
                href: https://argo.biggibson.cocotree.cc
                description: Continuous deployment
                icon: argocd.svg
          - Monitoring:
            - Grafana:
                href: https://grafana.biggibson.cocotree.cc
                description: Pretty charts letting me know when things blow up
                icon: grafana.svg
            - Prometheus:
                href: https://prometheus.biggibson.cocotree.cc
                description: Primary Grafana datasource
                icon: prometheus.svg
          - Utilities:
            - Excalidraw:
                href: https://draw.biggibson.cocotree.cc
                description: Virtual whiteboard
                icon: excalidraw.svg
            - Speedtest:
                href: https://speedtest.biggibson.cocotree.cc
                description: Internal network speed test
                icon: openspeedtest.png
        bookmarks.yaml: |
          - Homelab:
            - Public homelab repository:
              - href: https://github.com/captainsloths/gibsonkube
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
            - Tailscale:
              - href: https://login.tailscale.com/admin/
                icon: tailscale.svg
          - Infrastructure:
            - Router:
              - href: http://10.27.27.1
                icon: router.svg
            - Adguard:
              - href: http://10.27.27.1:81
                icon: adguard-home.svg
            - Proxmox:
              - href: https://gibson-virt.biggibson.cocotree.cc:8006
                icon: proxmox.svg
            - Palantir:
              - href: https://palantir.biggibson.cocotree.cc:8443
              - icon: ubiquiti.svg
