app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/excalidraw/excalidraw
            tag: latest
  service:
    main:
      ports:
        http:
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      hosts:
        - host: draw.biggibson.cocotree.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - draw.biggibson.cocotree.cc
