kube-prometheus-stack:
  grafana:
    adminPassword: null
    defaultDashboardsEnabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.biggibson.cocotree.cc
      tls:
        - hosts:
          - grafana.biggibson.cocotree.cc 
    persistence:
      enabled: false
    grafana.ini:
      server:
        root_url: http://grafana.biggibson.cocotree.cc
      auth.anonymous:
        enabled: false

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.biggibson.cocotree.cc
      tls:
        - hosts:
            - prometheus.biggibson.cocotree.cc
