app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/openspeedtest/latest
            tag: latest
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
      hosts:
        - host: &host speedtest.biggibson.cocotree.cc
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
